---
- name: Load OS distribution parameters
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/Linux.yml"

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_latest if docker_compose_version == "latest" else docker_compose_version }}/docker-compose-Linux-x86_64
    checksum: "{{ docker_compose_checksum }}"
    dest: "{{ docker_compose_path_os_default }}"
    mode: 0555
