---
- name: Load OS distribution parameters
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_system }}.yml"

- name: Install docker-compose
  get_url:
    url: "{{ docker_compose_url }}"
    checksum: "{{ docker_compose_checksum }}"
    dest: "{{ docker_compose_path | default(docker_compose_path_os_default) }}"
    mode: 0555
